name: torfin
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.0.0
  firebase_analytics: ^12.0.0
  firebase_crashlytics: ^5.0.0
  firebase_performance: ^0.11.0
  flutter_svg: ^2.2.0
  collection: ^1.19.1
  get_it: ^8.1.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  flutter_bloc: ^9.1.1
  dio: ^5.8.0+1
  uuid: ^4.5.1
  connectivity_plus: ^7.0.0
  flutter_torrent:
    git:
      url: https://github.com/udyan-dev/flutter_torrent.git
      ref: master
  path: ^1.9.1
  open_filex: ^4.7.0
  path_provider: ^2.1.5
  mime: ^2.0.0
  async: ^2.13.0
  external_path: ^2.2.0
  fuzzywuzzy: ^1.2.0
  permission_handler: ^12.0.1
  device_info_plus: ^12.1.0
  pretty_bytes: ^6.3.0
  duration: ^4.0.3
  in_app_review: ^2.0.11
  flutter_local_notifications: ^19.4.2
  url_launcher: ^6.3.2
  lottie: ^3.3.2
  google_mobile_ads: ^6.0.0
  flutter_secure_storage: ^9.2.4
  cloud_firestore: ^6.0.3
  file_picker: ^10.3.3
  content_resolver: ^0.3.6
  app_links: ^6.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.6.0
  freezed: ^3.2.0
  json_serializable: ^6.10.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/
    - assets/lottie/

  fonts:
    - family: IBM Plex Mono
      fonts:
        - asset: assets/fonts/IBMPlexMono-Regular.ttf
          weight: 400
    - family: IBM Plex Sans
      fonts:
        - asset: assets/fonts/IBMPlexSans-Light.ttf
          weight: 300
        - asset: assets/fonts/IBMPlexSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/IBMPlexSans-SemiBold.ttf
          weight: 600
